name: quizzical
description: Quizzical quiz app using Open Trivia DB API and optional Firebase backend.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  html_unescape: ^2.0.0
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/reference/
